# Generated by Django 5.2.6 on 2025-09-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = []
