# Generated by Django 5.2.6 on 2025-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_init_google_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="googleoauthtoken",
            name="id_token",
            field=models.TextField(default=255),
            preserve_default=False,
        ),
    ]
