# Generated by Django 5.2.6 on 2025-09-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_googleoauthtoken_id_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleoauthtoken",
            name="id_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
