name: CI (develop)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: google-api-project

    env:
      PYTHONPATH: .
      DJANGO_SETTINGS_MODULE: core.settings

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run unit tests (exceptions only)
        run: |
          poetry run pytest \
            tests/test_google_calendar_exceptions.py \
            tests/test_tasks_exceptions.py \
            tests/test_signals.py \
            --maxfail=1 --disable-warnings -q
